### ISSUE TITLE
membuat proposal

### ISSUE THREAD

**Issue by ajatsudrajat1** [ajatsudrajat1/ngeshift-ku-group4#3]
1. Deskripsi project
2. Team member and job desk
3. Buat simple flow diagram utk project yang akan dibuat
4. Timeline project
   note : 
   dokument dibuat pada google doc powerpoint dan dishare linknya ke email

**Comment by Hidayatulichwan** [comment]
https://docs.google.com/presentation/d/1q9mTESie__JRiZH5EddGEi0PsJ_n9EOV8FFMBm2zd48/edit#slide=id.p

**Comment by ajatsudrajat1** [comment]
ok...
